apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo-backend-pdb
  namespace: default
spec:
  minAvailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: demo-backend
