apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hy-k3d

image: rancher/k3s:v1.31.0-k3s1

servers: 1
agents: 3

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: '--disable=traefik'
        nodeFilters:
          - server:*
      - arg: '--disable=servicelb'
        nodeFilters:
          - server:*
      - arg: '--kubelet-arg=cgroup-driver=systemd'
        nodeFilters:
          - server:*
          - agent:*
  k3d:
    wait: true
    timeout: '180s'
    disableLoadbalancer: false

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true

  runtime:
    # 🔥 GPU 핵심 설정
    gpuRequest: all
