apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hy-k3d

image: rancher/k3s:v1.31.0-k3s1

servers: 1
agents: 3

# Dedicated Docker network (must exist before cluster create)
network: k3d-hy-k3d

kubeAPI:
  hostIP: '0.0.0.0'
  hostPort: '6443'

ports:
  # Ingress / Service 접근용
  - port: 18080:30080
    nodeFilters:
      - loadbalancer
  - port: 18443:30443
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: '--tls-san=127.0.0.1' # 인증서에 로컬 호스트 주소 포함
        nodeFilters: [server:0]
      - arg: '--disable=traefik'
        nodeFilters:
          - server:*
      - arg: '--disable=servicelb' # 내장 LB 비활성화
        nodeFilters: [server:*]

  k3d:
    wait: true
    timeout: '180s'
    disableLoadbalancer: false

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
