apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: hy-k3d

image: rancher/k3s:v1.31.0-k3s1

servers: 1
agents: 3

ports:
  # ✅ Kubernetes API Server (kubectl 접속용)
  - port: 6443:6443
    nodeFilters:
      - server:0
  # Ingress / Service 접근용
  - port: 18080:80
    nodeFilters:
      - loadbalancer
  - port: 18443:443
    nodeFilters:
      - loadbalancer

options:
  # k3s:
  #   extraArgs:
  #     - arg: "--disable=traefik"
  #       nodeFilters:
  #         - server:*
  #     - arg: "--disable=servicelb"
  #       nodeFilters:
  #         - server:*
  #     - arg: "--kubelet-arg=cgroup-driver=systemd"
  #       nodeFilters:
  #         - server:*
  #         - agent:*
  k3d:
    wait: true
    timeout: '180s'
    disableLoadbalancer: false

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
