# ============================================================================
# GitHub Sponsors 및 후원 설정 파일
#
# 목적:
# - 저장소 우측 사이드바에 "Sponsor" 버튼 표시
# - 여러 후원 플랫폼 링크를 한 곳에 모아서 관리
# - 오픈소스 프로젝트 유지를 위한 재정 지원 유도
#
# 표시 위치:
# - GitHub 저장소 메인 페이지 우측 상단 "Sponsor" 버튼
# - README 아래 자동으로 후원 옵션 표시
#
# 사용 가이드:
# 1. 사용하는 플랫폼만 활성화 (주석 제거)
# 2. 사용하지 않는 플랫폼은 주석 처리하거나 삭제
# 3. 개인 프로젝트에서 후원 안 받으면 이 파일 전체 삭제
#
# 공식 문서:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# ============================================================================

# ===========================================================================
# GitHub Sponsors (권장)
#
# 설명:
# - GitHub에 직접 통합된 후원 플랫폼
# - GitHub 계정으로 바로 후원 가능
# - 수수료가 없거나 낮음
# - 개인 계정 또는 조직 계정 지정 가능
#
# 사용법:
# - github: username (단일 계정)
# - github: [user1, user2, org1] (여러 계정, 최대 4개)
#
# GitHub Sponsors 설정:
# 1. https://github.com/sponsors 방문
# 2. "Join the waitlist" 또는 "Set up sponsorship" 클릭
# 3. 프로필, 티어, 결제 정보 설정
# 4. 여기에 username 입력
# ===========================================================================
# github: buenhyden
# github: [user1, user2]  # 여러 계정

# ===========================================================================
# Patreon
#
# 설명:
# - 월간 구독 기반 후원 플랫폼
# - 티어별 혜택 제공 가능
# - 크리에이터에게 인기
#
# 설정:
# 1. Patreon 계정 생성
# 2. 후원 페이지 설정
# 3. Patreon username 입력
#
# 예시: patreon: yourname
# ===========================================================================
# patreon: your-patreon-username

# ===========================================================================
# Open Collective
#
# 설명:
# - 투명한 재정 관리 플랫폼
# - 수입/지출 모두 공개
# - 오픈소스 프로젝트에 적합
# - 조직/프로젝트 단위 운영
#
# 설정:
# 1. Open Collective 프로젝트 생성
# 2. 프로젝트 slug 확인
# 3. 여기에 입력
#
# 예시: open_collective: project-name
# ===========================================================================
# open_collective: your-project

# ===========================================================================
# Ko-fi
#
# 설명:
# - "커피 한 잔 사주기" 스타일의 간단한 후원
# - 일회성 후원과 월간 후원 모두 지원
# - 설정이 간단함
#
# 설정:
# 1. Ko-fi 계정 생성
# 2. 후원 페이지 URL 확인
# 3. username 부분 입력
#
# URL 형식: ko-fi.com/username
# 예시: ko_fi: yourname
# ===========================================================================
# ko_fi: your-kofi-username

# ===========================================================================
# Tidelift
#
# 설명:
# - 엔터프라이즈 오픈소스 구독 플랫폼
# - 기업 사용자가 여러 OSS를 한 번에 후원
# - 보안 패치, 유지보수 보증 제공
#
# 사용법:
# - tidelift: npm/package-name
# - tidelift: pypi/package-name
#
# 주의: 패키지가 Tidelift에 등록되어 있어야 함
# ===========================================================================
# tidelift: npm/your-package
# tidelift: pypi/your-package

# ===========================================================================
# Community Bridge
#
# 설명:
# - Linux Foundation의 후원 플랫폼
# - 대형 오픈소스 프로젝트에 적합
# - 프로젝트 ID 필요
#
# community_bridge: project-id
# ===========================================================================
# community_bridge: your-project-id

# ===========================================================================
# Liberapay
#
# 설명:
# - 비영리 재발급형 후원 플랫폼
# - 주간 기반 후원
# - 수수료 최소화
#
# 설정:
# 1. Liberapay 계정 생성
# 2. username 확인
# 3. 여기에 입력
#
# 예시: liberapay: yourname
# ===========================================================================
# liberapay: your-username

# ===========================================================================
# IssueHunt
#
# 설명:
# - 이슈 해결에 대한 바운티 플랫폼
# - 특정 이슈에 현상금을 걸 수 있음
# - 개발자가 이슈 해결 후 보상 받음
#
# 사용법:
# - issuehunt: username (개인)
# - issuehunt: org/repo (저장소)
# ===========================================================================
# issuehunt: username

# ===========================================================================
# Otechie (Deprecated)
#
# 주의: Otechie는 2021년 서비스 종료
# Polar.sh 등 다른 플랫폼 사용 권장
# ===========================================================================
# otechie: username

# ===========================================================================
# LFX Mentorship (구 CommunityBridge)
#
# 설명:
# - Linux Foundation의 멘토십 프로그램
# - 프로젝트 ID 필요
# ===========================================================================
# lfx_crowdfunding: project-id

# ===========================================================================
# Custom URLs (커스텀 URL)
#
# 설명:
# - 위 플랫폼에 없는 후원 방법
# - 자체 후원 페이지, Buy Me a Coffee, PayPal 등
# - 최대 4개까지 가능
#
# 예시:
# - Buy Me a Coffee: https://buymeacoffee.com/username
# - PayPal: https://paypal.me/username
# - 자체 페이지: https://yoursite.com/donate
#
# 배열 형식으로 작성:
# custom: ["https://link1.com", "https://link2.com"]
# ===========================================================================
# custom: ["https://buymeacoffee.com/yourname"]
# custom: ["https://paypal.me/yourname", "https://yoursite.com/donate"]

# ============================================================================
# 권장 설정 (시작하기)
# ============================================================================
#
# 개인 개발자:
# 1. GitHub Sponsors (가장 통합도 높음)
# 2. Ko-fi (간단하고 빠름)
# 3. Custom URL (PayPal 등)
#
# 오픈소스 프로젝트:
# 1. Open Collective (투명성)
# 2. GitHub Sponsors
# 3. Tidelift (기업 후원)
#
# 조직:
# 1. GitHub Sponsors (조직 계정)
# 2. Open Collective
# 3. LFX Crowdfunding (대형 프로젝트)
#
# ============================================================================
# 플랫폼별 비교
# ============================================================================
#
# | 플랫폼 | 수수료 | 장점 | 단점 |
# |--------|--------|------|------|
# | GitHub Sponsors | 0% (처음 1년) | 통합도 | 지역 제한 |
# | Patreon | 5-12% | 티어 관리 | 수수료 높음 |
# | Open Collective | 10% | 투명성 | 설정 복잡 |
# | Ko-fi | 0% (Premium 월 $6) | 간단함 | 기능 제한 |
# | Tidelift | varies | 기업 후원 | 진입장벽 |
#
# ============================================================================
# 사용 팁
# ============================================================================
#
# 1. 너무 많은 옵션 제공 금지: 2-3개 플랫폼만 선택
# 2. 주력 플랫폼 먼저 나열: GitHub Sponsors 또는 Open Collective 먼저
# 3. 후원 용도 명시: README나 별도 페이지에서 후원금 사용처 설명
# 4. 갱신: 플랫폼 변경 시 이 파일도 업데이트
# 5. 테스트: 저장소에서 "Sponsor" 버튼이 제대로 보이는지 확인
#
# ============================================================================
