# ============================================================================
# Labeler 설정 (Labeler Configuration)
#
# 목적 (Purpose):
# - PR의 변경된 파일에 따라 자동 라벨 추가 (Auto-label PRs based on changed files)
# ============================================================================

# Applications
"apps":
  - "apps/**/*"

# Infrastructure
"infrastructure":
  - "infrastructure/**/*"

# Clusters
"clusters":
  - "clusters/**/*"

# Bootstrap
"bootstrap":
  - "bootstrap/**/*"

# Documentation
"documentation":
  - "**/*.md"
  - "docs/**/*"

# GitHub Settings
"github":
  - ".github/**/*"
