config:
  MD013: false
  MD025: false
  MD028: false
  MD036: false
  MD060:
    style: consistent
  MD033:
    allowed_elements:
      - div
      - br
      - p
  MD024: false
ignores:
  - '.agent/'
  - '.git/'
  - '.history/'
  - '.mypy_cache/'
  - '.vscode/'
  - 'node_modules/'
  - '.sisyphus/'
  - 'dist/'
  - 'coverage/'
  - 'storybook-static/'
# 자동 고침 활성화
fix: true
# 출력 포맷(선택)
# outputFormatters:
#   - - markdownlint-cli2-formatter-pretty
