apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-app-secret
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgres-app-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: db_name # pragma: allowlist secret
      remoteRef:
        key: platform/postgres-app
        property: db_name
    - secretKey: username # pragma: allowlist secret
      remoteRef:
        key: platform/postgres-app
        property: username
    - secretKey: password # pragma: allowlist secret
      remoteRef:
        key: platform/postgres-app
        property: password
