apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    platform.hyhome.io/validation-role: eso-read-platform
    platform.hyhome.io/validation-serviceaccount: external-secrets
    platform.hyhome.io/validation-namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault-external.platform.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-read-platform"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
