apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-service-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-service-2
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: backend-service-2-vs
            routes:
              - primary
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
  template:
    metadata:
      labels:
        app: backend-service-2
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: default # 필요 시 별도 SA 생성
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: app
          image: buenhyden/service-2:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            # --- Kafka 연결 설정 (External Service) ---
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-external:9092,kafka-external:9094,kafka-external:9096"
            - name: KAFKA_TOPIC
              value: "events"
            # --- Redis 연결 설정 (External Service) ---
            - name: REDIS_HOST
              value: "redis-external"
            - name: REDIS_PORT
              value: "6379" # Cluster 모드 시 초기 진입점
          # --- Secret 참조 (Password 등) ---
          envFrom:
            - secretRef:
                name: backend-2-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
