apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Workload applications only
  sourceRepos:
    - https://github.com/buenhyden/hy-home.k8s.git
  destinations:
    - namespace: apps
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ''
      kind: Service
    - group: networking.k8s.io
      kind: Ingress
    - group: external-secrets.io
      kind: ExternalSecret
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: security.istio.io
      kind: PeerAuthentication
    - group: networking.istio.io
      kind: VirtualService
    - group: networking.istio.io
      kind: DestinationRule
  roles:
    - name: apps-readonly
      policies:
        - p, proj:apps:apps-readonly, applications, get, apps/*, allow
      groups:
        - apps-readonly
