apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-platform
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/buenhyden/hy-home.k8s.git
    targetRevision: main
    path: gitops/apps/root
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
