name: 🐛 Bug Report
description: Create a report to help us improve the platform.
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!
  - type: textarea
    id: description
    attributes:
      label: 1. Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 2. Reproduction Steps
      description: |
        Please list steps or link to a minimal reproduction.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 3. Expected Behavior
      description:
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: 4. Environment
      description: OS, Browser, or Kubernetes version.
      placeholder: e.g. Windows / Docker Desktop K8s
  - type: textarea
    id: logs
    attributes:
      label: 5. Logs / Evidence
      description: Please paste logs or attach screenshots here.
      render: text
