name: Bug Report
description: Report a defect with reproducible details
title: '[BUG] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please provide enough detail to reproduce and validate the fix.
  - type: input
    id: spec_link
    attributes:
      label: Related Spec Link
      description: Link to the spec in `specs/` (if available)
      placeholder: https://github.com/<org>/<repo>/blob/main/specs/<file>.md
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Numbered steps with exact inputs
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, runtime, browser, app version
      placeholder: Ubuntu 24.04 / Node 20 / Chrome 122
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Initial impact estimate
      options:
        - low
        - medium
        - high
        - critical
    validations:
      required: true
  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics / Logs
      description: Paste relevant logs, trace IDs, or screenshots (redact secrets/PII).
    validations:
      required: false
