apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-store
  namespace: default
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://hyhome-kv.vault.azure.net/" # Replace with kvName output from Bicep
      serviceAccountRef:
        name: hyhome-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyhome-db-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: postgres-password # pragma: allowlist secret
    remoteRef:
      key: postgres-password
  - secretKey: redis-password # pragma: allowlist secret
    remoteRef:
      key: redis-password
