apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000" # Replace with appIdentity.properties.clientId from Bicep output
  name: hyhome-sa
  namespace: default
---
apiVersion: azure.workload.identity/v1
kind: FederatedIdentityCredential
metadata:
  name: hyhome-fed-id
  namespace: default
spec:
  audiences:
  - api://AzureADTokenExchange
  issuer: "https://oidc.azure.com/..." # Replace with aks.outputs.oidcIssuer from Bicep output
  subject: system:serviceaccount:default:hyhome-sa
