apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/buenhyden/hy-home.k8s.git
    targetRevision: eae3c3c8f248e5643c5b0f52beab3d072fc093e5
    path: gitops/clusters/local/00-argocd-projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
