apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-metallb-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: local
  source:
    repoURL: ssh://git@github.com/buenhyden/hy-home.k8s.git
    targetRevision: eae3c3c8f248e5643c5b0f52beab3d072fc093e5
    path: gitops/clusters/local/10-infra/metallb-install
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
