global:
  domain: argocd.127.0.0.1.nip.io

configs:
  params:
    server.insecure: true

dex:
  enabled: false

redis:
  enabled: false

externalRedis:
  host: valkey-external.platform.svc.cluster.local
  port: 6379
  existingSecret: argocd-external-valkey # pragma: allowlist secret
  passwordKey: redis-password # pragma: allowlist secret

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.127.0.0.1.nip.io
    tls: false
    extraTls:
      - hosts:
          - argocd.127.0.0.1.nip.io
        secretName: argocd-local-tls # pragma: allowlist secret

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true
