global:
  domain: argocd.local

configs:
  params:
    server.insecure: true

redis:
  enabled: false

externalRedis:
  host: valkey-external.platform.svc.cluster.local
  port: 26379
  existingSecret: argocd-external-valkey
  passwordKey: redis-password

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.local
    tls:
      - hosts:
          - argocd.local
        secretName: argocd-local-tls

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true
