global:
  domain: argo.hy-k8s.home.arpa

configs:
  cm:
    timeout.reconciliation: 30s
  params:
    server.insecure: true

dex:
  enabled: false

redis:
  enabled: false

externalRedis:
  host: valkey-external.platform.svc.cluster.local
  port: 6379
  existingSecret: argocd-external-valkey # pragma: allowlist secret
  passwordKey: redis-password # pragma: allowlist secret

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argo.hy-k8s.home.arpa
    tls: false
    extraTls:
      - hosts:
          - argo.hy-k8s.home.arpa
        secretName: argocd-local-tls # pragma: allowlist secret

notifications:
  enabled: true
  metrics:
    enabled: true

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true
