apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-git-ssh
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  # encryptedData is intended for kubeseal output. Do not place private keys here.
  # Run the following (locally) and paste the output encryptedData:
  # kubectl -n argocd create secret generic argocd-git-ssh --from-file=sshPrivateKey=./id_rsa --dry-run=client -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
  encryptedData:
    sshPrivateKey: <SEALED_DATA_HERE>
# NOTES:
#  - Do not commit private keys or unencrypted secrets into Git.
#  - Generate a key locally with `ssh-keygen -t rsa -b 4096 -f ./id_rsa -N ''`.
#  - Add the public key to your Git host as a deploy key with write access.
#  - Use the kubeseal command above to create the sealed secret YAML with your cluster's public key.
#  - The controller name/namespace may differ depending on your Sealed Secrets installation; adjust accordingly.
