apiVersion: v1
kind: Secret
metadata:
  name: argocd-git-ssh
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  # DO NOT ADD REAL PRIVATE KEYS HERE — this is a template. Use `kubectl create secret` instead.
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    <YOUR_PRIVATE_KEY>
    -----END OPENSSH PRIVATE KEY-----

# Usage:
# 1) Create a secret on your local machine instead of committing private keys:
#    kubectl -n argocd create secret generic argocd-git-ssh \
#      --from-file=sshPrivateKey=./id_rsa
# 2) Tell ArgoCD to use this key when adding the repo:
#    argocd repo add git@github.com:buenhyden/hy-home.k8s.git --ssh-private-key-path ./id_rsa
# 3) Or create a repository entry in the ArgoCD UI using the SSH key.
#
# NOTE: Prefer SealedSecret or SOPS encrypted templates for storing sensitive data in Git.
# Use clusters/docker-desktop/argocd-git-ssh-sealedsecret-template.yaml or
# clusters/docker-desktop/argocd-git-ssh-sops-template.yaml instead if you will store
# encrypted secrets in the repo.
