apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-external-valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: argocd-external-valkey
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: redis-password
      remoteRef:
        key: platform/argocd
        property: valkey_password
