#!/usr/bin/env bash
# k8s-pre-edit.sh — warn before editing Kubernetes, secrets, or authored docs.
# Runs at PreToolUse for Write|Edit|MultiEdit. Exits 0 always (non-blocking).
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
INPUT="$(cat || true)"
export PROJECT_DIR INPUT CLAUDE_TOOL_INPUT_FILE_PATH="${CLAUDE_TOOL_INPUT_FILE_PATH:-}" CLAUDE_TOOL_INPUT="${CLAUDE_TOOL_INPUT:-}"

python3 - <<'PY'
import json
import os
import re

project_dir = os.environ.get("PROJECT_DIR", "")
raw = os.environ.get("INPUT", "")
if not raw.strip():
    raw = os.environ.get("CLAUDE_TOOL_INPUT", "")

paths: list[str] = []


def add_path(value):
    if isinstance(value, str) and value.strip():
        path = value.strip()
        if project_dir and path.startswith(project_dir + "/"):
            path = path[len(project_dir) + 1 :]
        if path.startswith("./"):
            path = path[2:]
        if path not in paths:
            paths.append(path)


try:
    data = json.loads(raw) if raw.strip() else {}
except Exception:
    data = {}

tool_input = data.get("tool_input", {}) if isinstance(data, dict) else {}
if isinstance(tool_input, dict):
    add_path(tool_input.get("file_path") or tool_input.get("path"))
    for key in ("files", "paths"):
        value = tool_input.get(key)
        if isinstance(value, list):
            for item in value:
                if isinstance(item, str):
                    add_path(item)
                elif isinstance(item, dict):
                    add_path(item.get("file_path") or item.get("path"))

    edits = tool_input.get("edits")
    if isinstance(edits, list):
        for edit in edits:
            if isinstance(edit, dict):
                add_path(edit.get("file_path") or edit.get("path"))

add_path(os.environ.get("CLAUDE_TOOL_INPUT_FILE_PATH", ""))

manifest_re = re.compile(
    r"(gitops/.*\.ya?ml|infrastructure/.*\.ya?ml|examples/sample-app/.*\.ya?ml|"
    r"examples/.*/gitops/.*\.ya?ml|examples/.*/kubernetes/.*\.ya?ml|traefik/.*\.ya?ml)$"
)
secret_re = re.compile(r"(secret|credential|password|token)", re.IGNORECASE)


def authored_doc_template(path: str) -> str:
    if not path.endswith(".md"):
        return ""
    if path.startswith("docs/00.agent-governance/") or path.startswith("docs/99.templates/"):
        return ""
    if path == "docs/90.references/llm-wiki/wiki-index.md":
        return "generated by scripts/generate-llm-wiki-index.sh; do not edit by hand"
    if re.match(r"^docs/(01\.requirements|02\.architecture|03\.specs|04\.execution|05\.operations|90\.references)(/|$)", path):
        if path.endswith("/README.md"):
            return "docs/99.templates/readme.template.md"
        basename = path.rsplit("/", 1)[-1]
        if path.startswith("docs/01.requirements/"):
            return "docs/99.templates/prd.template.md"
        if path.startswith("docs/02.architecture/requirements/"):
            return "docs/99.templates/ard.template.md"
        if path.startswith("docs/02.architecture/decisions/"):
            return "docs/99.templates/adr.template.md"
        if path.startswith("docs/03.specs/"):
            spec_templates = {
                "spec.md": "docs/99.templates/spec.template.md",
                "api-spec.md": "docs/99.templates/api-spec.template.md",
                "agent-design.md": "docs/99.templates/agent-design.template.md",
                "data-model.md": "docs/99.templates/data-model.template.md",
                "tests.md": "docs/99.templates/tests.template.md",
            }
            return spec_templates.get(basename, "classify via docs/99.templates/README.md before writing")
        if path.startswith("docs/04.execution/plans/"):
            return "docs/99.templates/plan.template.md"
        if path.startswith("docs/04.execution/tasks/"):
            return "docs/99.templates/task.template.md"
        if path.startswith("docs/05.operations/guides/"):
            return "docs/99.templates/guide.template.md"
        if path.startswith("docs/05.operations/policies/"):
            return "docs/99.templates/operation.template.md"
        if path.startswith("docs/05.operations/runbooks/"):
            return "docs/99.templates/runbook.template.md"
        if path.startswith("docs/05.operations/incidents/postmortems/"):
            return "docs/99.templates/postmortem.template.md"
        if re.match(r"^docs/05\.operations/incidents/[0-9]{4}/", path):
            return "docs/99.templates/incident.template.md"
        if path.startswith("docs/90.references/"):
            return "docs/99.templates/reference.template.md"
        return "classify via docs/99.templates/README.md before writing"
    return ""


messages: list[str] = []
for path in paths:
    if manifest_re.search(path):
        messages.append(
            "\n".join(
                [
                    f"Editing Kubernetes manifest `{path}`.",
                    "- Keep the change GitOps-first: repository review -> ArgoCD reconciliation.",
                    "- Do not introduce plaintext Kubernetes secrets.",
                    "- The PostToolUse hook will run manifest and secret-handling validation.",
                ]
            )
        )
    if secret_re.search(path):
        messages.append(
            "\n".join(
                [
                    f"File name is secret-adjacent: `{path}`.",
                    "- Never write plaintext secret values.",
                    "- Use ExternalSecret or SealedSecret-style patterns only.",
                ]
            )
        )
    template = authored_doc_template(path)
    if template:
        if template.startswith("generated by "):
            messages.append(
                "\n".join(
                    [
                        f"Editing generated documentation `{path}`.",
                        f"- This path is {template}.",
                        "- Route policy or procedure changes to the canonical owner document instead.",
                        "- The PostToolUse hook will run documentation template enforcement.",
                    ]
                )
            )
        else:
            messages.append(
                "\n".join(
                    [
                        f"Editing authored documentation `{path}`.",
                        "- Template-First is mandatory: confirm the mapping in `docs/99.templates/README.md`.",
                        f"- Required template: `{template}`.",
                        "- New authored docs must keep `status: draft`, required template headings, and `## Related Documents`.",
                        "- Folder-level adds, moves, or removals require the owning `README.md` to be updated in the same change.",
                        "- The PostToolUse hook will run documentation template enforcement.",
                    ]
                )
            )

if messages:
    print(json.dumps({"systemMessage": "\n\n".join(messages)}))
PY

exit 0
