#!/usr/bin/env bash
# k8s-pre-edit.sh — warn before editing Kubernetes, secrets, or authored docs.
# Runs at PreToolUse for Write|Edit|MultiEdit. Invalid path transport fails closed.
set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
INPUT_FILE="$(mktemp)"
PATHS_FILE="$(mktemp --suffix=.nul)"
SELECT_LOG="$(mktemp)"
trap 'rm -f "$INPUT_FILE" "$PATHS_FILE" "$SELECT_LOG"' EXIT
cat >"$INPUT_FILE"
export PROJECT_DIR INPUT_FILE PATHS_FILE CLAUDE_TOOL_INPUT_FILE_PATH="${CLAUDE_TOOL_INPUT_FILE_PATH:-}" CLAUDE_TOOL_INPUT="${CLAUDE_TOOL_INPUT:-}"

python3 - <<'PY'
import json
import os
import re
import sys
from pathlib import Path, PurePosixPath

project_dir = os.environ.get("PROJECT_DIR", "")
raw = Path(os.environ["INPUT_FILE"]).read_text(encoding="utf-8")
if not raw:
    raw = os.environ.get("CLAUDE_TOOL_INPUT", "")

paths: list[str] = []


def reject(code: str) -> None:
    print(f"[FAIL] {code}", file=sys.stderr)
    raise SystemExit(2)


def add_path(value):
    if not isinstance(value, str) or not value:
        reject("HOOK-PATH-TYPE")
    if any(ord(character) < 32 or ord(character) == 127 for character in value):
        reject("HOOK-PATH-CONTROL")
    if value[0].isspace() or value[-1].isspace():
        reject("HOOK-PATH-WHITESPACE")

    path = value
    if path.startswith("/"):
        prefix = project_dir.rstrip("/") + "/"
        if not project_dir or not path.startswith(prefix):
            reject("HOOK-PATH-ROOT")
        path = path[len(prefix) :]
    posix = PurePosixPath(path)
    if (
        not path
        or path.startswith("./")
        or path.endswith("/")
        or "//" in path
        or "\\" in path
        or posix.is_absolute()
        or "." in posix.parts
        or ".." in posix.parts
        or posix.as_posix() != path
    ):
        reject("HOOK-PATH-NORMALIZATION")

    cursor = Path(project_dir)
    for part in posix.parts:
        cursor /= part
        if cursor.is_symlink():
            reject("HOOK-PATH-SYMLINK")
    if path not in paths:
        paths.append(path)


try:
    data = json.loads(raw) if raw else {}
except (TypeError, json.JSONDecodeError):
    reject("HOOK-PAYLOAD-JSON")
if not isinstance(data, dict):
    reject("HOOK-PAYLOAD-SHAPE")


def consume_scalar_alias(mapping) -> int:
    present = [key for key in ("file_path", "path") if key in mapping]
    for key in present:
        if not isinstance(mapping[key], str) or not mapping[key]:
            reject("HOOK-PATH-TYPE")
    if len(present) > 1:
        reject("HOOK-PATH-ALIAS")
    if present:
        add_path(mapping[present[0]])
    return len(present)


if "tool_input" in data and not isinstance(data["tool_input"], dict):
    reject("HOOK-PAYLOAD-SHAPE")
tool_input = data.get("tool_input", {})
scalar_count = consume_scalar_alias(tool_input)
collection_aliases = [key for key in ("files", "paths") if key in tool_input]
for key in collection_aliases:
    value = tool_input[key]
    if not isinstance(value, list):
        reject("HOOK-PATH-LIST")
    if any(not isinstance(item, str) or not item for item in value):
        reject("HOOK-PATH-TYPE")
if len(collection_aliases) > 1 or (scalar_count and collection_aliases):
    reject("HOOK-PATH-ALIAS")
for key in collection_aliases:
    value = tool_input[key]
    for item in value:
        add_path(item)

if "edits" in tool_input:
    edits = tool_input["edits"]
    if not isinstance(edits, list):
        reject("HOOK-PATH-LIST")
    for edit in edits:
        if not isinstance(edit, dict):
            reject("HOOK-PATH-TYPE")
        consume_scalar_alias(edit)

environment_path = os.environ.get("CLAUDE_TOOL_INPUT_FILE_PATH", "")
if environment_path:
    add_path(environment_path)
Path(os.environ["PATHS_FILE"]).write_bytes(
    b"".join(path.encode("utf-8") + b"\0" for path in paths)
)

manifest_re = re.compile(
    r"(gitops/.*\.ya?ml|infrastructure/.*\.ya?ml|examples/sample-app/.*\.ya?ml|"
    r"examples/.*/gitops/.*\.ya?ml|examples/.*/kubernetes/.*\.ya?ml|traefik/.*\.ya?ml)$"
)
secret_re = re.compile(r"(secret|credential|password|token)", re.IGNORECASE)


def authored_doc_template(path: str) -> str:
    if not path.endswith(".md"):
        return ""
    if path.startswith("docs/00.agent-governance/") or path.startswith("docs/99.templates/"):
        return ""
    if path == "docs/90.references/llm-wiki/wiki-index.md":
        return "generated by scripts/generate-llm-wiki-index.sh; do not edit by hand"
    if re.match(r"^docs/(01\.requirements|02\.architecture|03\.specs|04\.execution|05\.operations|90\.references|98\.archive)(/|$)", path):
        if path.endswith("/README.md"):
            return "classify via docs/99.templates/support/document-profiles.json and docs/99.templates/support/template-routing.md before writing"
        basename = path.rsplit("/", 1)[-1]
        if path.startswith("docs/01.requirements/"):
            return "docs/99.templates/templates/sdlc/requirements/prd.template.md"
        if path.startswith("docs/02.architecture/requirements/"):
            return "docs/99.templates/templates/sdlc/architecture/ard.template.md"
        if path.startswith("docs/02.architecture/decisions/"):
            return "docs/99.templates/templates/sdlc/architecture/adr.template.md"
        if path.startswith("docs/03.specs/"):
            spec_templates = {
                "spec.md": "docs/99.templates/templates/sdlc/specs/spec.template.md",
                "api-spec.md": "docs/99.templates/templates/sdlc/specs/api-spec.template.md",
                "agent-design.md": "docs/99.templates/templates/sdlc/specs/agent-design.template.md",
                "data-model.md": "docs/99.templates/templates/sdlc/specs/data-model.template.md",
                "tests.md": "docs/99.templates/templates/sdlc/specs/tests.template.md",
            }
            return spec_templates.get(basename, "classify via docs/99.templates/support/template-routing.md before writing")
        if path.startswith("docs/04.execution/plans/"):
            return "docs/99.templates/templates/sdlc/execution/plan.template.md"
        if path.startswith("docs/04.execution/tasks/"):
            return "docs/99.templates/templates/sdlc/execution/task.template.md"
        if path.startswith("docs/05.operations/guides/"):
            return "docs/99.templates/templates/sdlc/operations/guide.template.md"
        if path.startswith("docs/05.operations/policies/"):
            return "docs/99.templates/templates/sdlc/operations/policy.template.md"
        if path.startswith("docs/05.operations/runbooks/"):
            return "docs/99.templates/templates/sdlc/operations/runbook.template.md"
        if re.match(r"^docs/05\.operations/incidents/[0-9]{4}/INC-[0-9]{3}-[^/]+/postmortem\.md$", path):
            return "docs/99.templates/templates/sdlc/operations/postmortem.template.md"
        incident_match = re.match(
            r"^docs/05\.operations/incidents/[0-9]{4}/(?P<folder>INC-[0-9]{3}-[^/]+)/(?P<filename>INC-[0-9]{3}-[^/]+\.md)$",
            path,
        )
        if incident_match:
            folder = incident_match.group("folder")
            filename = incident_match.group("filename")
            if filename == f"{folder}.md":
                return "docs/99.templates/templates/sdlc/operations/incident.template.md"
            return "classify via docs/99.templates/support/template-routing.md; incident filename must match the incident folder"
        if path.startswith("docs/90.references/"):
            return "docs/99.templates/templates/common/reference.template.md"
        if path.startswith("docs/98.archive/"):
            return "docs/99.templates/templates/common/archive-tombstone.template.md"
        return "classify via docs/99.templates/support/template-routing.md before writing"
    return ""


messages: list[str] = []
for path in paths:
    if manifest_re.search(path):
        messages.append(
            "\n".join(
                [
                    f"Editing Kubernetes manifest `{path}`.",
                    "- Keep the change GitOps-first: repository review -> ArgoCD reconciliation.",
                    "- Do not introduce plaintext Kubernetes secrets.",
                    "- The PostToolUse hook will run manifest and secret-handling validation.",
                ]
            )
        )
    if secret_re.search(path):
        messages.append(
            "\n".join(
                [
                    f"File name is secret-adjacent: `{path}`.",
                    "- Never write plaintext secret values.",
                    "- Use ExternalSecret or SealedSecret-style patterns only.",
                ]
            )
        )
    template = authored_doc_template(path)
    if template:
        if template.startswith("generated by "):
            messages.append(
                "\n".join(
                    [
                        f"Editing generated documentation `{path}`.",
                        f"- This path is {template}.",
                        "- Route policy or procedure changes to the canonical owner document instead.",
                        "- The PostToolUse hook will run documentation template enforcement.",
                    ]
                )
            )
        else:
            route_line = (
                f"- Required template: `{template}`."
                if not template.startswith("classify via ")
                else f"- Route note: `{template}`."
            )
            messages.append(
                "\n".join(
                    [
                        f"Editing authored documentation `{path}`.",
                        "- Template-First is mandatory: confirm the route in `docs/99.templates/support/template-routing.md`; use `docs/99.templates/README.md` as the inventory summary.",
                        route_line,
                        "- New authored docs must keep `status: draft`, required template headings, and the registry-selected relationship section.",
                        "- Folder-level adds, moves, or removals require the owning `README.md` to be updated in the same change.",
                        "- The PostToolUse hook will run documentation template enforcement.",
                    ]
                )
            )

if messages:
    print(json.dumps({"systemMessage": "\n\n".join(messages)}))
PY

if ! python3 "$PROJECT_DIR/scripts/select-affected-surfaces.py" \
  --root "$PROJECT_DIR" --lane affected --paths-file "$PATHS_FILE" \
  --delimiter nul --format json >"$SELECT_LOG" 2>&1; then
  python3 - <<'PY'
import json

print(json.dumps({"systemMessage": "Affected-surface selection rejected an edit path. Normalize it to one repository-relative POSIX path and update the canonical surface contract before editing."}))
PY
  exit 2
fi

exit 0
