apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps-default-deny.yaml
  - apps-allow-dns-egress.yaml
  - apps-allow-ingress-from-ingress-nginx.yaml
  - home-default-deny.yaml
  - home-allow-dns-egress.yaml
  - home-allow-ingress-from-ingress-nginx.yaml
