apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-external-services
  namespace: platform
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.19.0.9/32
      ports:
        - protocol: TCP
          port: 8200
    - to:
        - ipBlock:
            cidr: 172.19.0.11/32
      ports:
        - protocol: TCP
          port: 15432
        - protocol: TCP
          port: 15433
    - to:
        - ipBlock:
            cidr: 172.19.0.12/32
      ports:
        - protocol: TCP
          port: 26379
