apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kiali-egress-to-observability
  namespace: istio-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kiali
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.19.0.20/32
      ports:
        - protocol: TCP
          port: 9090
    - to:
        - ipBlock:
            cidr: 172.19.0.24/32
      ports:
        - protocol: TCP
          port: 3000
    - to:
        - ipBlock:
            cidr: 172.19.0.22/32
      ports:
        - protocol: TCP
          port: 3200
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
