apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-namespaces-app.yaml
  - platform-external-services-app.yaml
  - platform-network-policies-app.yaml
  - platform-external-secrets-operator-app.yaml
  - platform-cert-manager-app.yaml
  - platform-istio-base-app.yaml
  - platform-eso-config-app.yaml
  - platform-ingress-nginx-app.yaml
  - platform-cert-manager-config-app.yaml
  - platform-istiod-app.yaml
  - platform-headlamp-app.yaml
  - platform-headlamp-config-app.yaml
  - platform-rollouts-app.yaml
  - platform-argocd-config-app.yaml
  - platform-kiali-app.yaml
  - platform-kiali-config-app.yaml
  - platform-monitoring-app.yaml
