apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: https://github.com/buenhyden/hy-home.k8s.git
    targetRevision: main
    path: gitops/platform/network-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
