# --- PostgreSQL ---
apiVersion: v1
kind: Service
metadata:
  name: postgres-write
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 15432
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-write
  namespace: default
subsets:
  - addresses:
      - ip: 172.19.0.60
    ports:
      - port: 15432
---
# --- Redis ---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: default
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 172.19.0.30
    ports:
      - port: 6379
---
# --- Kafka ---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  namespace: default
spec:
  ports:
    - port: 9092
      targetPort: 9092
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 172.19.0.11
    ports:
      - port: 9092
---
# --- OpenSearch ---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: default
spec:
  ports:
    - port: 9200
      targetPort: 9200
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: opensearch
  namespace: default
subsets:
  - addresses:
      - ip: 172.19.0.40
    ports:
      - port: 9200