apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault-external.yaml
  - postgres-external.yaml
  - valkey-external.yaml
  - prometheus-external.yaml
  - loki-external.yaml
  - tempo-external.yaml
  - alloy-external.yaml
  - grafana-external.yaml
