apiVersion: v1
kind: Service
metadata:
  name: postgres-write-external
  namespace: platform
spec:
  ports:
    - name: postgres-write
      port: 15432
      targetPort: 15432
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: postgres-write-external-1
  namespace: platform
  labels:
    kubernetes.io/service-name: postgres-write-external
addressType: IPv4
ports:
  - name: postgres-write
    protocol: TCP
    port: 15432
endpoints:
  - addresses:
      - 172.19.0.11
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-read-external
  namespace: platform
spec:
  ports:
    - name: postgres-read
      port: 15433
      targetPort: 15433
  type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: postgres-read-external-1
  namespace: platform
  labels:
    kubernetes.io/service-name: postgres-read-external
addressType: IPv4
ports:
  - name: postgres-read
    protocol: TCP
    port: 15433
endpoints:
  - addresses:
      - 172.19.0.11
